name: Documentation
on:
  push:
    branches: [main]
permissions:
  contents: write

jobs:
  build:
    name: Generate and publish website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Build
        run: sphinx-build -b dirhtml -v docs _build

      - name: Remove .doctrees
        run: rm -r _build/.doctrees

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/docs/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
